FROM payara/server-full:5.194

ADD --chown=payara:payara https://jdbc.postgresql.org/download/postgresql-42.2.11.jar /opt/payara/appserver/glassfish/domains/production/lib

COPY domain-dev.xml /opt/payara/appserver/glassfish/domains/production/config/domain.xml
