FROM jboss/wildfly:18.0.1.Final

RUN /opt/jboss/wildfly/bin/add-user.sh admin admin --silent

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]

COPY target/*.war /opt/jboss/wildfly/standalone/deployments/
