pipeline {
    agent any
    environment {
        VERSION = """${sh(
            returnStdout:true,
            script: 'echo 0.0.0'
        )}"""
    }
    stages {
        stage('Test') {
            when {
                not {
                    branch 'master'
                }
            }
            steps {
                dir('Unity/StickmanCharades') {
                    sh 'echo Skipping...'
                }
            }
        }
        stage('Build') {
            when {
                branch 'master'
            }
            steps {
                sh 'echo Skipping...'
            }
        }
        stage('Publish') {
            when {
                branch 'master'
            }
            steps {
                sh 'echo Skipping...'
            }
        }
    }
}
