FROM node:13.11.0 AS build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json /app

RUN npm install --only=prod
RUN npm install @angular/cli@~9.1.0

COPY . /app

RUN ng build --prod --output-path=dist && rm -r node_modules

FROM nginx:1.17.9

COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx
